"""add indexes on user_id, sort_order, category

Revision ID: e30c057282df
Revises: 18ac9071f974
Create Date: 2026-05-21 20:55:47.900481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30c057282df'
down_revision: Union[str, Sequence[str], None] = '18ac9071f974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('todos', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('todos', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('todos', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_todos_user_category', 'todos', ['user_id', 'category'], unique=False)
    op.create_index(op.f('ix_todos_user_id'), 'todos', ['user_id'], unique=False)
    op.create_index('ix_todos_user_sort', 'todos', ['user_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todos_user_sort', table_name='todos')
    op.drop_index(op.f('ix_todos_user_id'), table_name='todos')
    op.drop_index('ix_todos_user_category', table_name='todos')
    op.alter_column('todos', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('todos', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('todos', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
